export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=

export MONGODB_ATLAS_PUBLIC_KEY=
export MONGODB_ATLAS_PRIVATE_KEY=
export TF_VAR_mongo_db_password=
export TF_VAR_mongo_db_username=
export TF_VAR_mongo_organization_id=

export TF_VAR_github_personal_access_token=
export TF_VAR_jwt_secret_key=
